### ISSUE TITLE
contrib.cache.RedisClient doesn't allow setting a key without a ttl

### ISSUE THREAD

**Issue by emidln** [mitsuhiko/werkzeug#550]
I'd expect that setting the default_timeout of RedisClient to None (or 0) would result in a SET being issued instead of a SETEX (i.e. no timeout). As is, a SETEX is issued with an invalid timeout.

Is this feature something that would be accepted into werkzeug? If so, I can whip up a patch to do this.

**Comment by thirty3** [comment]
This has been idle for some time, I'm happy to pick it

**Comment by untitaker** [comment]
Please do so! You have full freedom in how to implement this, but some things are important:

* Backwards compatibility -- if we're going to break it, then we'll have to wait until a major release (which is probably not what you want)
* Testcases
* Consistent API across cache implementations (add a testcase to `tests.contrib.test_cache.CacheTests` to get it tested against all implementations)

**Comment by thirty3** [comment]
I had a read for the caching code particularly from a Memcached point of view and noticed this problem.

If default_timeout is 0 I would expect the values to not timeout at all. Currently if it is 0 it will cause a value to timeout immediately on Memcached.

I'm proposing changing cache so that a timeout of 0 will cause the cache to never expire.

Is that OK?

**Comment by untitaker** [comment]
I wouldn't expect anybody to rely on the current behavior of `timeout=0`, so that's fine by me. Please make sure to clarify in the docs between `timeout=None` and `timeout=0` though.
