### ISSUE TITLE
Test client does not handle WSGI iterator correctly

### ISSUE THREAD

**Issue by aop** [mitsuhiko/werkzeug#712]
As described in the new relic forums [1] it seems that tests run with certain libraries such as the New Relic Python agent expose a bug. The client doesn't convert an iterable to an iterator.

I've tried this with versions 
Flask==0.10.1
Werkzeug==0.9.6

[1] https://discuss.newrelic.com/t/werkzeug-cant-work-properly-when-using-agent-2-40-0-34/13318/4

**Comment by davidism** [comment]
There is nothing on that page.  Can you post the relevant description of the problem *here* rather than linking to another place?

**Comment by untitaker** [comment]
@davidism Scroll down to Graham's response.

This is definely a bug.

**Comment by davidism** [comment]
It must be my browser, there is literally no content on the linked page.

**Comment by untitaker** [comment]
Just for clarity, with a particular WSGI application, a NewRelic customer encountered this particular traceback:

      File "/Users/kakashi/Programs/project/.env/lib/python2.7/site-packages/werkzeug/test.py", line 873, in run_wsgi_app
        buffer.append(next(app_iter))
    TypeError: _WSGIApplicationIterable object is not an iterator

As noted further down in the thread, this happens because `werkzeug.test.run_wsgi_app` expects an WSGI apps' return value to be an iterator, while according to the WSGI spec, it might as well be an *iterable*.

--

However, simply returning an iterable isn't enough for this bug to be triggered, the start_response call must also happen *after* the iterable has been returned.

**Comment by untitaker** [comment]
See #713
